name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      AUTH_IDUFFS_TEST_USERNAME: ${{ secrets.AUTH_IDUFFS_TEST_USERNAME }}
      AUTH_IDUFFS_TEST_PASSOWRD: ${{ secrets.AUTH_IDUFFS_TEST_PASSOWRD }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run tests
        run: ./vendor/bin/pest